// -*- mode: c++ -*-
// 
// File MDF_CARBON_MC_3_73_mwpc_6_WithTx.C generated by TMultiDimFit::MakeRealCode
// on Tue Nov 22 15:43:20 2022
// ROOT version 6.26/02
//
// This file contains the function 
//
//    double  MDF(double *x); 
//
// For evaluating the parameterization obtained
// from TMultiDimFit and the point x
// 
// See TMultiDimFit class documentation for more information 
// 
//
// Static data variables
//
static int    gNVariables    = 10;
static int    gNCoefficients = 30;
static double gDMean         = 7.55294;
// Assignment to mean vector.
static double gXMean[] = {
  0.00214874, -0.0185712, -0.0060118, -0.00136134, -0.0300802, -0.156349, -0.0794181, 0.000396678, -0.314673, -0.154338 };

// Assignment to minimum vector.
static double gXMin[] = {
  -9.54469, -9.48509, -387.162, -0.0199998, -0.02, 5.88408, -28.0473, 495.201, 0.0548038, -0.0435648 };

// Assignment to maximum vector.
static double gXMax[] = {
  9.47119, 9.54283, -216.272, 0.0199999, 0.0199997, 125.978, 32.0266, 735.2, 0.237388, 0.0599121 };

// Assignment to coefficients vector.
static double gCoefficient[] = {
  -1.90701,
  -3.44607,
  0.110651,
  2.1152,
  0.678817,
  -0.929038,
  -1.48092,
  0.861504,
  -0.257546,
  0.083324,
  1.23181,
  -0.771593,
  -0.0608968,
  0.014332,
  -0.0698226,
  -0.0303224,
  0.424843,
  -0.395568,
  0.70322,
  0.0323373,
  0.050854,
  -0.0311376,
  0.186256,
  0.0150887,
  0.0414573,
  0.372735,
  0.184527,
  -0.227575,
  0.191755,
  -0.104783
 };

// Assignment to error coefficients vector.
static double gCoefficientRMS[] = {
  2.48834e-11,
  7.43646e-11,
  5.41334e-11,
  2.02184e-10,
  3.81603e-11,
  1.14499e-10,
  3.54509e-10,
  2.53846e-10,
  9.44974e-11,
  3.50699e-11,
  4.37652e-10,
  3.63886e-10,
  1.59085e-10,
  5.84737e-11,
  1.26731e-10,
  4.55144e-11,
  2.16491e-10,
  5.21216e-10,
  6.16185e-10,
  7.65274e-11,
  1.52335e-10,
  4.20025e-11,
  2.2088e-10,
  1.08419e-10,
  5.22785e-11,
  7.4097e-10,
  5.62969e-10,
  3.69186e-10,
  1.65947e-10,
  2.45754e-10
 };

// Assignment to powers vector.
// The powers are stored row-wise, that is
//  p_ij = gPower[i * NVariables + j];
static int    gPower[] = {
  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
  1,  1,  1,  1,  1,  1,  1,  1,  2,  1,
  2,  1,  1,  1,  1,  1,  1,  1,  1,  1,
  1,  1,  1,  1,  1,  1,  1,  1,  3,  1,
  1,  1,  1,  2,  1,  1,  1,  1,  1,  1,
  1,  1,  1,  2,  1,  1,  1,  1,  2,  1,
  1,  1,  1,  1,  1,  1,  1,  1,  4,  1,
  1,  1,  1,  2,  1,  1,  1,  1,  3,  1,
  1,  1,  1,  3,  1,  1,  1,  1,  2,  1,
  1,  1,  1,  3,  1,  1,  1,  1,  1,  1,
  1,  1,  1,  1,  1,  1,  1,  1,  5,  1,
  1,  1,  1,  2,  1,  1,  1,  1,  4,  1,
  1,  1,  1,  1,  1,  1,  1,  1,  1,  2,
  2,  1,  2,  1,  1,  1,  1,  1,  1,  1,
  2,  1,  1,  1,  1,  1,  1,  1,  2,  1,
  1,  1,  1,  1,  4,  1,  1,  1,  1,  1,
  1,  1,  1,  3,  1,  1,  1,  1,  3,  1,
  1,  1,  1,  1,  1,  1,  1,  1,  6,  1,
  1,  1,  1,  2,  1,  1,  1,  1,  5,  1,
  1,  1,  1,  1,  1,  1,  2,  1,  1,  1,
  1,  1,  1,  1,  1,  1,  1,  1,  2,  2,
  1,  1,  2,  2,  1,  1,  1,  1,  1,  1,
  2,  1,  1,  1,  1,  1,  1,  1,  3,  1,
  1,  1,  1,  1,  1,  1,  3,  1,  2,  1,
  1,  1,  2,  2,  1,  1,  1,  1,  2,  1,
  1,  1,  1,  1,  1,  1,  1,  1,  1,  5,
  1,  1,  1,  1,  1,  1,  1,  1,  4,  2,
  1,  1,  1,  1,  1,  1,  2,  1,  3,  2,
  2,  1,  1,  1,  1,  1,  2,  1,  3,  1,
  1,  1,  1,  1,  2,  2,  1,  1,  3,  1
};

// 
// The function   double MDF(double *x)
// 
double MDF(double *x) {
  double returnValue = gDMean;
  int    i = 0, j = 0, k = 0;
  for (i = 0; i < gNCoefficients ; i++) {
    // Evaluate the ith term in the expansion
    double term = gCoefficient[i];
    for (j = 0; j < gNVariables; j++) {
      // Evaluate the polynomial in the jth variable.
      int power = gPower[gNVariables * i + j]; 
      double p1 = 1, p2 = 0, p3 = 0, r = 0;
      double v =  1 + 2. / (gXMax[j] - gXMin[j]) * (x[j] - gXMax[j]);
      // what is the power to use!
      switch(power) {
      case 1: r = 1; break; 
      case 2: r = v; break; 
      default: 
        p2 = v; 
        for (k = 3; k <= power; k++) { 
          p3 = p2 * v;
          p1 = p2; p2 = p3; 
        }
        r = p3;
      }
      // multiply this term by the poly in the jth var
      term *= r; 
    }
    // Add this term to the final result
    returnValue += term;
  }
  return returnValue;
}

// EOF for MDF_CARBON_MC_3_73_mwpc_6_WithTx.C
