// -*- mode: c++ -*-
// 
// File MDF_Tx_CARBON_MC_3_73_mwpc_5.C generated by TMultiDimFit::MakeRealCode
// on Tue Nov 22 13:25:51 2022
// ROOT version 6.26/02
//
// This file contains the function 
//
//    double  MDF(double *x); 
//
// For evaluating the parameterization obtained
// from TMultiDimFit and the point x
// 
// See TMultiDimFit class documentation for more information 
// 
//
// Static data variables
//
static int    gNVariables_TX    = 9;
static int    gNCoefficients_TX = 30;
static double gDMean_TX         = -0.000466346;
// Assignment to mean vector.
static double gXMean_TX[] = {
  -0.0100228, -0.00695333, -0.0102561, -0.00362439, -0.133868, 0.0461199, 0.000825485, 0.2926, -0.303596 };

// Assignment to minimum vector.
static double gXMin_TX[] = {
  -9.54469, -9.48509, -387.162, -0.02, 5.88408, -35.9834, 495.201, -0.113095, -0.166503 };

// Assignment to maximum vector.
static double gXMax_TX[] = {
  9.50156, 9.58143, -215.421, 0.0199999, 125.978, 33.2468, 735.2, 0.248711, 0.313817 };

// Assignment to coefficients vector.
static double gCoefficient_TX[] = {
  0.0342092,
  -0.0114069,
  0.0510426,
  0.504903,
  0.040437,
  -0.0329729,
  -0.219968,
  -0.0908657,
  -0.053579,
  -0.0222836,
  -4.77463,
  -0.00304551,
  0.0279252,
  -0.00796611,
  0.00448271,
  0.0176267,
  -0.28513,
  -20.9617,
  -0.492491,
  0.0114805,
  0.00818373,
  0.753562,
  -0.00317055,
  -0.000998331,
  -0.00187812,
  -18.4651,
  0.137393,
  -0.05253,
  -0.0165634,
  -0.026126
 };

// Assignment to error coefficients vector.
static double gCoefficientRMS_TX[] = {
  4.48974e-11,
  8.2551e-11,
  1.24517e-10,
  4.80762e-10,
  2.59825e-10,
  3.36606e-10,
  4.10749e-10,
  2.57796e-10,
  1.53515e-10,
  2.12421e-10,
  1.70866e-09,
  8.06811e-11,
  2.34965e-10,
  2.68717e-10,
  3.25068e-11,
  2.37502e-10,
  1.16984e-09,
  1.39724e-08,
  3.39339e-09,
  1.43193e-10,
  3.72934e-10,
  1.08556e-08,
  6.80257e-11,
  2.20235e-10,
  9.49256e-11,
  5.01518e-09,
  2.17836e-09,
  1.15677e-09,
  5.09693e-10,
  3.48154e-09
 };

// Assignment to powers vector.
// The powers are stored row-wise, that is
//  p_ij = gPower_TX[i * NVariables_TX + j];
static int    gPower_TX[] = {
  1,  1,  1,  1,  1,  1,  1,  1,  1,
  2,  1,  1,  1,  1,  1,  1,  1,  1,
  1,  1,  1,  1,  2,  1,  1,  1,  1,
  1,  1,  1,  1,  1,  1,  1,  2,  2,
  1,  1,  1,  1,  1,  1,  2,  1,  2,
  1,  1,  1,  1,  1,  2,  1,  1,  2,
  1,  1,  1,  1,  2,  1,  1,  1,  2,
  1,  1,  1,  1,  1,  1,  1,  3,  1,
  1,  1,  1,  1,  1,  1,  2,  2,  1,
  1,  1,  1,  1,  1,  2,  1,  2,  1,
  1,  1,  1,  1,  1,  1,  1,  1,  4,
  1,  1,  1,  1,  1,  1,  2,  1,  1,
  1,  1,  1,  1,  2,  1,  1,  2,  1,
  2,  1,  1,  1,  1,  1,  1,  2,  1,
  2,  1,  2,  1,  1,  1,  1,  1,  1,
  1,  1,  1,  1,  1,  1,  2,  3,  1,
  1,  1,  1,  1,  1,  1,  1,  4,  2,
  1,  1,  1,  1,  1,  1,  1,  1,  6,
  1,  1,  1,  1,  2,  1,  1,  3,  3,
  1,  1,  1,  1,  2,  2,  1,  1,  1,
  1,  1,  1,  1,  1,  2,  2,  2,  1,
  1,  1,  1,  1,  1,  1,  1,  2,  5,
  1,  1,  1,  1,  1,  2,  2,  1,  1,
  2,  1,  1,  1,  1,  2,  1,  2,  1,
  4,  1,  1,  1,  1,  1,  1,  1,  1,
  1,  1,  1,  1,  1,  1,  1,  1,  5,
  2,  1,  1,  1,  1,  1,  1,  1,  4,
  2,  1,  1,  1,  1,  1,  1,  3,  2,
  1,  1,  1,  1,  1,  2,  2,  3,  1,
  1,  1,  1,  2,  1,  1,  1,  1,  5
};

// 
// The function   double MDF(double *x)
// 
double MDF_TX(double *x) {
  double returnValue = gDMean_TX;
  int    i = 0, j = 0, k = 0;
  for (i = 0; i < gNCoefficients_TX ; i++) {
    // Evaluate the ith term in the expansion
    double term = gCoefficient_TX[i];
    for (j = 0; j < gNVariables_TX; j++) {
      // Evaluate the polynomial in the jth variable.
      int power = gPower_TX[gNVariables_TX * i + j]; 
      double p1 = 1, p2 = 0, p3 = 0, r = 0;
      double v =  1 + 2. / (gXMax_TX[j] - gXMin_TX[j]) * (x[j] - gXMax_TX[j]);
      // what is the power to use!
      switch(power) {
      case 1: r = 1; break; 
      case 2: r = v; break; 
      default: 
        p2 = v; 
        for (k = 3; k <= power; k++) { 
          p3 = p2 * v;
          p1 = p2; p2 = p3; 
        }
        r = p3;
      }
      // multiply this term by the poly in the jth var
      term *= r; 
    }
    // Add this term to the final result
    returnValue += term;
  }
  return returnValue;
}

// EOF for MDF_Tx_CARBON_MC_3_73_mwpc_5.C
